def get_topic_msg_key(topic, msg_id, delimiter: str = ...): ...
def get_topic_msg_read_key(topic, msg_id, sub_id, delimiter: str = ...): ...
def get_topic_key_pattern(topic, delimiter: str = ...): ...
def extract_msg_id_from_topic_msg_key(topic_msg_key): ...
def write_msg(topic, msg_id, msg, ttl: int = ...) -> None: ...
def get_msg(topic, msg_id): ...
def get_msg_by_key(topic_msg_key): ...
def pop_msg(topic, msg_id): ...
def mark_msg_as_read(topic, msg_id, sub_id) -> None: ...
def is_msg_read(topic, msg_id, sub_id): ...
def get_msgs_for_topic(topic) -> None: ...
